# Generated by Django 4.1.3 on 2023-06-20 08:08

import django.core.validators
from django.db import migrations, models
import plant_app.accounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, validators=[plant_app.accounts.models.name_validator])),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, validators=[plant_app.accounts.models.name_validator])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
