# Generated by Django 4.1.3 on 2023-06-20 09:10

from django.db import migrations, models
import plant_app.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='first_name',
            field=models.CharField(max_length=30, null=True, validators=[plant_app.accounts.models.name_validator]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='last_name',
            field=models.CharField(max_length=30, null=True, validators=[plant_app.accounts.models.name_validator]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_picture',
            field=models.URLField(null=True),
        ),
    ]
